project_id = "qpufyeeqosvgipslwday"

[functions.tikwm-scraper]
verify_jwt = false

[functions.apify-scraper]
verify_jwt = false

[functions.apify-webhook]
verify_jwt = false

[functions.youtube-oauth]
verify_jwt = false

[functions.youtube-upload]
verify_jwt = false

[functions.process-queue]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.schedule-processor]
verify_jwt = false
